# Generated by Django 4.0.3 on 2023-02-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author_user',
            new_name='review_user',
        ),
    ]
